# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$Qb1I27j/KXLTM9R36p4.kOkjQbWV.mAR62GYSr1GmsCD1yg49fkwm
                        roles: ROLE_ADMIN

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

    access_control:
        - { path: ^/(fr|en)/admin, roles: ROLE_ADMIN }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

            form_login:
                login_path: security.login
                check_path: security.login
                #default_target_path: admin.homepage.index
                default_target_path: security.redirect.by.role
                failure_path: homepage.public.index
            logout:
                path: security.logout
                target: homepage.public.index

            provider: in_memory


            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /admin
                always_remember_me: true


